# Site settings
title: Arjun Shakdher
description: Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Arjun Shakdher
user_description: Arjun is passionate about blending technology into the fabric of life. Holding a master’s degree from Purdue University, Arjun’s current role revolves around researching, architecting and developing cutting-edge prototypes that span an array of domains, presently featuring the realms of Artificial Intelligence / Machine Learning. When not immersed in code and digital landscapes, you’ll find Arjun indulging in the world of coffee, exploring the intricate mechanics of horology, or reveling in the artistry of automobiles.
user_title: Research, Development & Architecture | Protoyping
email: arjunshakdher@gmail.com
# twitter_username: lorem_ipsum
instagram_username: arjunshakdher
# facebook_username: arjunshakdher
linkedin_username: arjunshakdher
github_username:  arjunshakdher
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

